name: CI
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@ec106b438a1ff6ff109590de34ddc62c540232e0
      with:
        ruby-version: 2.7.0
    - name: Install dependencies
      run: |
        checkout
        cache restore
        sem-version ruby 2.7.0
        bundle install --deployment -j 4 --path vendor/bundle
        yarn install --pure-lockfile
        cache store
